general:
  public_url: http://localhost:8080
  api_key: some_secret_api_key
  secret_key: some_secret_key

database:
  host: postgres

rabbitmq:
  host: rabbitmq

email:
  host: mailpit
  port: 1025

playout:
  liquidsoap_host: liquidsoap

liquidsoap:
  server_listen_address: 0.0.0.0

  harbor_ssl_certificate: /certs/fake.crt
  harbor_ssl_private_key: /certs/fake.key

stations:
  - id: 1
    name: "Nina.fm Mont-Blanc"
    stream:
      inputs:
        main:
          public_url: https://localhost:8001/nina-mont-blanc
          mount: nina-mont-blanc
          port: 8001
          secure: true
        show:
          mount: show-nina-mont-blanc
          port: 8002

      outputs:
        .default_icecast_output: &default_icecast_output
          host: icecast
          port: 8000
          source_password: hackme
          admin_password: hackme
          name: Nina.fm - Mont-Blanc
          description: LibreTime Nina.fm Mont-Blanc
          website: https://libretime.org
          genre: various

        icecast:
          - <<: *default_icecast_output
            enabled: true
            mount: nina-mont-blanc.ogg
            public_url: https://localhost:8443/nina-mont-blanc.ogg
            audio:
              format: ogg
              bitrate: 256

          - <<: *default_icecast_output
            enabled: true
            mount: nina-mont-blanc.mp3
            public_url: https://localhost:8443/nina-mont-blanc.mp3
            audio:
              format: mp3
              bitrate: 128

        system:
          - enabled: false
            kind: pulseaudio

  - id: 2
    name: "Nina.fm City Beach"
    stream:
      inputs:
        main:
          mount: nina-city-beach
          port: 8003
        show:
          mount: show-nina-city-beach
          port: 8004

      outputs:
        icecast:
          - <<: *default_icecast_output
            enabled: true
            mount: nina-city-beach.ogg
            public_url: https://localhost:8443/nina-city-beach.ogg
            audio:
              format: ogg
              bitrate: 256

          - <<: *default_icecast_output
            enabled: true
            mount: nina-city-beach.mp3
            public_url: https://localhost:8443/nina-city-beach.mp3
            audio:
              format: mp3
              bitrate: 128
